### ISSUE TITLE
Compile Error with Universal Definition Data Module

### ISSUE THREAD

**Issue by maytheu** [Epistimis/universal-data-definition-language#11]
In [Conceptual Characteristics](https://github.com/Epistimis/universal-data-definition-language/blob/master/src/language-server/validation/conceptualDataModel/conceptualCharacteristic.ts), the getIdentityContribution() when isConceptualParticipant() is true return getIdentityContributionOfParticipents() which is not defined, so th getIdentityContributionOfParticipents() cannot be found

The [Conceptual Participant](https://github.com/Epistimis/universal-data-definition-language/blob/master/src/language-server/validation/conceptualDataModel/conceptualParticipants.ts) contains error in isPathNodeResolvable(), isPathNodeResolvable() is not referenced, the isPathNodeResolvable() in the [conceptualPathNode](https://github.com/Epistimis/universal-data-definition-language/blob/master/src/language-server/validation/conceptualDataModel/conceptualPathNode.ts) is not type compatible

1. cd to  uddl_test/uddl_test_formatting/
2. npx jest universal-data-definition-language-formatter.test.ts

**Expected behavior**
The test suite should run and pass

**Comment by steve-hickman-epistimis** [comment]
Assuming this is resolved
